routes/frontend.php
<?php
/**
 * Created by PhpStorm.
 * User: shruti
 * Date: 11/12/19
 * Time: 3:15 PM
 */

use Illuminate\Support\Facades\App;

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function (){
    Route::get('/', 'HomeController@index')->name('home.index');

    Route::get('news/{id}', function ($id) {
        return view('frontend.news.newsDetail', ['id'=> $id]);
    });

    Route::get('category/{id}', function ($id) {
        return App::call('App\Http\Controllers\Frontend\ProductController@getCategory', ['id' => $id]);
    });

    Route::get('services/{id}', function ($id) {
        return App::call('App\Http\Controllers\Frontend\ProductController@getProduct', ['id' => $id]);
    });

    Route::get('projects/{id}', function ($id) {
        return App::call('App\Http\Controllers\Frontend\ProjectsController@getProjects', ['id' => $id]);
    });

    Route::get('projectDetail/{id}', function ($id) {
        return App::call('App\Http\Controllers\Frontend\ProjectsController@projectDetail', ['id' => $id]);
    });

    Route::get('apply/{id}', function ($id) {
        return App::call('App\Http\Controllers\Frontend\ServiceRequestController@apply', ['id' => $id]);
    });

    Route::any('categories', 'ProductController@getAllCategories')->name('categories');
    Route::any('services', 'ProductController@index')->name('products');
    Route::any('projects', 'ProjectsController@index')->name('projects');
    Route::get('news', 'NewsController@index')->name('news');

    Route::get('login', 'CustomerController@index')->name('login');
    Route::post('authCheck', 'CustomerController@login')->name('authCheck');

    Route::get('register', 'CustomerController@register')->name('register');
    Route::get('checkEmail', 'CustomerController@checkEmail')->name('checkEmail');
    Route::get('checkVAT_no', 'CustomerController@checkVAT_no')->name('checkVAT_no');
    Route::post('save', 'CustomerController@save')->name('save');

    Route::get('forgot-password', 'ForgotPasswordController@forgotPassword')->name('forgotPassword');
    Route::post('email-reset-password-link', 'ForgotPasswordController@emailResetPasswordLink')->name('emailResetPasswordLink');
    Route::get('reset-password-form/{token}', 'ForgotPasswordController@resetPasswordForm')->name('resetPasswordForm');
    Route::post('save-password', 'ForgotPasswordController@savePassword')->name('savePassword');

    // request access
    Route::group(['middleware' => ['FrontendAuth','Security']], function(){

        Route::get('resetpassword', 'CustomerController@resetpassword')->name('resetpassword');
        Route::post('updatepassword', 'CustomerController@updatepassword')->name('updatepassword');

        Route::post('submitRequest', 'ServiceRequestController@submitRequest')->name('submitRequest');
        Route::get('applyNotification', 'ServiceRequestController@applyNotification')->name('applyNotification');

        Route::post('getDraftData', 'ServiceRequestController@getDraftData')->name('getDraftData');
        Route::post('applyService', 'ServiceRequestController@applyService')->name('applyService');
        Route::post('deleteDocument','ServiceRequestController@deleteDocument')->name('deleteDocument');

        Route::get('home-logout', 'CustomerController@logout')->name('logout');
    });

    Route::get('/{slug}', 'SegmentController@index')->name('cms.index');
});

routes/web.php
        Route::get('consulting-service-products/edit/{id}','Voyager\\ConsultingServiceProductController@edit')->name('voyager.consulting-service-products.edit');
        Route::put('consulting-service-products/update/{id}','Voyager\\ConsultingServiceProductController@update')->name('voyager.consulting-service-products.update');
        Route::delete('consulting-service-products/destroy/{id}','Voyager\\ConsultingServiceProductController@destroy')->name('voyager.consulting-service-products.destroy');

        // Projects
        Route::get('projects','Voyager\\ProjectsController@index')->name('voyager.projects.index');
        Route::post('projects','Voyager\\ProjectsController@index')->name('voyager.projects');
        Route::post('projects/browse','Voyager\\ProjectsController@browse')->name('voyager.projects.browse');
        Route::get('projects/create','Voyager\\ProjectsController@create')->name('voyager.projects.create');
        Route::post('projects/store','Voyager\\ProjectsController@store')->name('voyager.projects.store');
        Route::get('projects/edit/{id}','Voyager\\ProjectsController@edit')->name('voyager.projects.edit');
        Route::put('projects/update/{id}','Voyager\\ProjectsController@update')->name('voyager.projects.update');
        Route::delete('projects/destroy/{id}','Voyager\\ProjectsController@destroy')->name('voyager.projects.destroy');

        // Footer Widgets
        Route::get('footer-widgets','Voyager\\FooterWidgetsController@index')->name('voyager.footer-widgets.index');
        Route::post('footer-widgets','Voyager\\FooterWidgetsController@index')->name('voyager.footer-widgets');
        Route::post('footer-widgets/browse','Voyager\\FooterWidgetsController@browse')->name('voyager.footer-widgets.browse');
        Route::get('footer-widgets/create','Voyager\\FooterWidgetsController@create')->name('voyager.footer-widgets.create');
        Route::post('footer-widgets/store','Voyager\\FooterWidgetsController@store')->name('voyager.footer-widgets.store');
        Route::get('footer-widgets/edit/{id}','Voyager\\FooterWidgetsController@edit')->name('voyager.footer-widgets.edit');
        Route::put('footer-widgets/update/{id}','Voyager\\FooterWidgetsController@update')->name('voyager.footer-widgets.update');
        Route::delete('footer-widgets/destroy/{id}','Voyager\\FooterWidgetsController@destroy')->name('voyager.footer-widgets.destroy');


        /* ProductCategoriesController */
        Route::get('product-categories','Voyager\\ProductCategoriesController@index')->name('voyager.product-categories.index');
        Route::post('product-categories','Voyager\\ProductCategoriesController@index')->name('voyager.product-categories');
        Route::post('product-categories/browse','Voyager\\ProductCategoriesController@browse')->name('voyager.product-categories.browse');
        Route::get('product-categories/create','Voyager\\ProductCategoriesController@create')->name('voyager.product-categories.create');
        Route::post('product-categories/store','Voyager\\ProductCategoriesController@store')->name('voyager.product-categories.store');
        Route::get('product-categories/edit/{id}','Voyager\\ProductCategoriesController@edit')->name('voyager.product-categories.edit');
        Route::put('product-categories/update/{id}','Voyager\\ProductCategoriesController@update')->name('voyager.product-categories.update');
        Route::delete('product-categories/destroy/{id}','Voyager\\ProductCategoriesController@destroy')->name('voyager.product-categories.destroy');

        // Admin Media
//        Route::get('media/', ['uses' => 'Voyager\\VoyagerMediaController@index',              'as' => 'index']);
//        Route::post('files', ['uses' => 'Voyager\\VoyagerMediaController@files',              'as' => 'files']);
//        Route::post('new_folder', ['uses' => 'Voyager\\VoyagerMediaController@new_folder',         'as' => 'new_folder']);
//        Route::post('delete_file_folder', ['uses' => 'Voyager\\VoyagerMediaController@delete', 'as' => 'delete']);
//        Route::post('move_file', ['uses' => 'Voyager\\VoyagerMediaController@move',          'as' => 'move']);
//        Route::post('rename_file', ['uses' => 'Voyager\\VoyagerMediaController@rename',        'as' => 'rename']);
//        Route::post('upload', ['uses' => 'Voyager\\VoyagerMediaController@upload',             'as' => 'upload']);
//        Route::post('crop', ['uses' => 'Voyager\\VoyagerMediaController@crop',             'as' => 'crop']);

    });

});
Route::get('service-inquiries/ajaxCityList','Frontend\\CustomerController@ajaxCityList')->name('voyager.service-inquiries.ajaxCityList');
Route::get('invitation_check_dock/{id}', function($id){
//    try {
        $service_data = ServiceInquiryVerification::where('link', decrypt($id))->first();
        $serviceInquiryData = ServiceInquiries::where('id',$service_data->service_inquiry_id)->first();
        $service_form_data = [];
        $filesList = json_decode($service_data->path);
        foreach(json_decode($serviceInquiryData->fields) as $key => $form_data){
            if ($form_data->type == 'file'){
                $fileName = ServiceInquiriesDocuments::where('service_inquiries_id', $serviceInquiryData->id)->where('document', 'LIKE', $form_data->name.'%')->first();

                $customerFolder = $serviceInquiryData->user->name .'_'. $serviceInquiryData->user->id;
                $serviceInquiryVerificationId = $serviceInquiryData->id;
                $docPath = 'Documents/' . $customerFolder . '/' . $serviceInquiryVerificationId . '/' . $fileName->document;

                if($fileName){
                    if(in_array($fileName->document,array_values((Array)$filesList))) {
                        array_push($service_form_data, [
                            'type' => $form_data->type,
                            'title' => $form_data->label,
                            'value' => url('customerAttachmentDownload'). '?path='.$docPath
//                            'value' => asset('storage/documents/' . $fileName->document)
                        ]);
                    }
                }
            } else if($form_data->type == 'paragraph' || $form_data->type == 'header' || $form_data->type == 'hidden' || $form_data->type == 'button'){}else{
                try{
                    array_push($service_form_data,[
                        'type' => $form_data->type,
                        'title'  => $form_data->label,
                        'value'  => implode(', ', $form_data->userData)
                    ]);
                } catch (\Exception $s){
                    continue;
                }
            }
        }
        return view('frontend.tempUrl.verification', compact('service_data', 'service_form_data'));
//    }catch (Exception $e){
//        return abort(404);
//    }
})->name('invitationServiceInquiryVerification');

Route::any('action-services-inquiry-verification/{id}', function(\Illuminate\Http\Request $request, $id){
    app()->setLocale('kz');
    $docName = [];
    if($request->external_doc) {
        foreach ($request->external_doc as $key => $extDoc) {
            $image = $extDoc;
            $path = 'public/serviceInquiry/externalVerification/';
            $fileName = \Carbon\Carbon::now()->timestamp.$key. '.' . $image->getClientOriginalExtension();
            $storeFileName = 'serviceInquiry/externalVerification/' . $fileName;
            Storage::disk('local')->put($path . $fileName, file_get_contents($image));
            array_push($docName, $storeFileName);
        }
    }
    $service_data = ServiceInquiryVerification::where('id',$id)->first();
    $service_data->is_verified = $request->status == 1 ? ServiceInquiryVerification::VERIFICATION_YES : ServiceInquiryVerification::VERIFICATION_NO;
    $service_data->action_taken_at = \Carbon\Carbon::now();
    $service_data->comment = $request->comment;
    $service_data->documents = json_encode($docName);
    $service_data->save();

    ServiceInquiryActivity::create([
        'service_inquiry_id' => $service_data->service_inquiry_id,
        'user_id' => 0,
        'activity_type' => ServiceInquiryActivity::ACTIVITY_VERIFICATION,
        'message' => json_encode(['is_verified' => $service_data->is_verified, 'action_taken_at' => $service_data->action_taken_at, 'comment' => $service_data->comment, 'email' => $service_data->email, 'documents' => json_encode($docName)]),
        'requested_param' => serialize($request->except(['external_doc'])),
    ]);

    return back();
})->name('actionServiceInquiryVerification');

Route::post('CustomerFile', 'Voyager\\ServiceInquiryController@customerFile')->name('customerFile');

//Route::get('admin/login', ['uses' => 'Voyager\\VoyagerAuthController@login',     'as' => 'voyager.login']);
Route::get('admin/login', 'Frontend\CustomerController@index')->name('voyager.login');
Route::post('admin/login', ['uses' => 'Voyager\\VoyagerAuthController@postLogin', 'as' => 'voyager.postlogin']);

Route::get('customerAttachmentDownload',function(\Illuminate\Http\Request $request){

    /* DOWNLOAD FILE */
    try {
        $files = Storage::disk('sftp')->download($request->path);
        return $files;
    } catch (\Exception $e) {
        \Illuminate\Support\Facades\Log::notice('FILE DOWNLOAD ERROR '. $e->getMessage());
        return back();
    }
})->name('customerAttachmentDownload');

Route::get('download-file',function(\Illuminate\Http\Request $request){
//    dd($request->path);
//    $file = '/mig/savan.txt';
//    $content = 'BAITEREK 2020 PROJECT';
    /* STORE FILE */
//    Storage::disk('sftp')->put($file, $content);
    /****************END *****************/

    /* DOWNLOAD FILE */

    try {
        $files = Storage::disk('sftp')->download($request->path);
        return $files;
    } catch (\Exception $e) {
        \Illuminate\Support\Facades\Log::notice('FILE DOWNLOAD ERROR '. $e->getMessage());
        return back();
    }

app/Http/Controllers/Frontend/CMSController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Helper\Helper;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use TCG\Voyager\Facades\Voyager;
use TCG\Voyager\Http\Controllers\Traits\BreadRelationshipParser;
use TCG\Voyager\Models\Page;

class CMSController extends \TCG\Voyager\Http\Controllers\Controller
{
    use BreadRelationshipParser;

    public function index(){

    }
}

app/Http/Controllers/Frontend/ForgotPasswordController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Helper\Helper;
use App\Http\Controllers\Controller;
use App\Mail\Forgotpassword;
use App\Models\User;
use Illuminate\Auth\Events\PasswordReset;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class ForgotPasswordController extends Controller
{
    public function index(){

    }

    public function forgotPassword(){
        return view('frontend.auth.forgotpassword');
    }

    public function emailResetPasswordLink(Request $request)
    {
        $this->validate($request, [
            'email' => 'required|email',
        ]);

        if(!$user = User::whereEmail($request->email)->first()){
            return redirect(route('frontend.forgotPassword'))->with('error', trans('validation.email not found'));
        } else {

            if(empty($user->remember_token)) {
                $user->remember_token = Helper::generateRememberToken($user->email);
                $user->save();
            }

            $passwordResetModel = new \App\Models\PasswordReset();
            $passwordResetModel->email = $user->email;
            $passwordResetModel->token = $user->remember_token;
            $passwordResetModel->save();
        }

        $email = $user->email;
        $resetPasswordLink = route('frontend.resetPasswordForm',['token' => $user->remember_token]);

        if(!empty($email)){
            $userLang = app()->getLocale();
            Mail::to($email)->send(new Forgotpassword($user->name,$user->remember_token,$resetPasswordLink,$userLang));
            if( count(Mail::failures()) == 0 ) {
                return redirect(route('frontend.forgotPassword'))->with('success', trans('validation.reset password link send'));
            }
        }
    }

    public function resetPasswordForm($token)
    {
        $user = \App\Models\PasswordReset::where('token',$token)->first();
        if(!$user){
            return redirect(route('frontend.home.index'))->with('error', trans('validation.link expire'));
        }
        return view('frontend.auth.forgotResetPassword',compact('token'));
    }

    public function savePassword(Request $request)
    {
        $this->validate($request, [
            'password' => 'min:6|required',
            'confirm_password' => 'min:6|required_with:password|same:password'
        ]);

        $user = \App\Models\PasswordReset::where('token',$request->token)->first();

        if ($user) {
            // Update password
            $password = $request->password;

            $users = User::where('email',$user->email)->first();
            $users->setPasswordAttribute($password);
            $users->save();

            $passwordRestModel = \App\Models\PasswordReset::where('email',$user->email)->first();

            // Delete the row from password reset table
            $passwordRestModel->where('email',$user->email)->forceDelete();

            return redirect(route('frontend.login'))->with('success',trans('passwords.New password set successfully'));

        } else {
            // Redirect forgot password page with error message
            return redirect(route('frontend.login'))->with('error','This link is no longer available');
        }

    }
}

app/Http/Controllers/Frontend/HomeController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index()
    {
        return view('frontend.master');
    }
}

app/Http/Controllers/Frontend/NewsController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\News;
use Illuminate\Http\Request;

class NewsController extends Controller
{
    public function index(){
        $news = News::all();

        return view('frontend.news.news',array('news' => $news));
    }
}

resources/views/frontend/layouts/categories.blade.php
<div class="col-md-12">
    <h3 class="section-header">@lang('fields.Browse Services')</h3>
    {{-- <p class="section-para">Imperdiet pulvinar ut nunc pellentesque.</p> --}}

    {{--<form class="">--}}
{{--        {{csrf_field()}}--}}
        <input class="form-control search-here" id="search-category" type="search" placeholder="@lang('fields.Search')" aria-label="Search">
    {{--</form>--}}
    <div class="services-list categoryList">
        <ul class="owl-carousel myCarousel owl_catagory">
            @if(!empty(\App\Http\Controllers\Services::getAllProductCategories('4')))
                @foreach(\App\Http\Controllers\Services::getAllProductCategories('4') as $productCategory)
                    <li class="item">
                        <a href="{{url('category', ['id' => $productCategory->id])}}">
                            <div class="service-box">
                                <div class="serice-icon"> <i class="icon-{{$productCategory->logo}}"></i></div>
                                <h5>{{$productCategory->title}}</h5>
                                <p>{{$productCategory->description}}</p>
                                <div class="background-icon"><i class="icon-{{$productCategory->logo}}"></i></div>
                            </div>
                        </a>
                    </li>
                @endforeach
            @endif
        </ul>
        <a href="{{url('categories')}}" class="view-all btn">@lang('fields.View All')</a>
    </div>
</div>

resources/views/frontend/layouts/companylogos.blade.php
@if(!empty(\App\Helper\Helper::getBannerCategoryBySlug('company-logos')))
<div class="col-md-12">
    <ul>
        @foreach(\App\Helper\Helper::getBannersImages('company-logos') as $companybanners)
            <li>
                <img src="{{asset('storage/' . $companybanners->image)}}" class="img-fluid" alt="">
            </li>
        @endforeach
    </ul>
</div>
@endif

resources/views/frontend/layouts/footer.blade.php
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <ul class="footer-links">
                <li class="footer-links-li">
                    @if(!empty(\App\Helper\Helper::getFooterWidget('digital-baiterek')))
                        <p>{!! \App\Helper\Helper::getFooterWidget('digital-baiterek')->content !!}</p>
                    @endif
                </li>
                <li class="footer-links-li">
                    {{-- <h6 class="color-white">Explore</h6> --}}
                    {{menu('Footer menu Block 1','bootstrap')}}
                </li>
                <li class="footer-links-li">
                    @if(!empty(\App\Helper\Helper::getFooterWidget('visit')))
                        {{-- <h6 class="color-white">{{\App\Helper\Helper::getFooterWidget('visit')->title}}</h6> --}}
                        <p>{!! \App\Helper\Helper::getFooterWidget('visit')->content !!}</p>
                    @endif
                </li>
                {{-- <li class="footer-links-li">
                    @if(!empty(\App\Helper\Helper::getFooterWidget('new-business')))
                        <h6 class="color-white">{{\App\Helper\Helper::getFooterWidget('new-business')->title}}</h6>
                        <p>{!! \App\Helper\Helper::getFooterWidget('new-business')->content !!}</p>
                    @endif
                </li> --}}
                <li class="footer-links-li">
                    {{-- <h6 class="color-white">legal</h6> --}}
                    {{menu('Footer menu Block 2','bootstrap')}}
                </li>
                <li class="footer-links-li">
                    @if(!empty(\App\Helper\Helper::getFooterWidget('contact')))
                        {{-- <h6 class="color-white">{!! \App\Helper\Helper::getFooterWidget('contact')->title !!}</h6> --}}
                        <p>{!! \App\Helper\Helper::getFooterWidget('contact')->content !!}</p>
                    @endif
                </li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="footer-copyright">
                <p>© @lang('content.copy_rights') {{Carbon\Carbon::createFromFormat('Y-m-d H:i:s', \Carbon\Carbon::now())->year}} @lang('content.all_rights')</p>
                {{-- <p>Created by <a href="">AVDEVS Solution</a></p> --}}
            </div>
        </div>
    </div>
</div>

resources/views/frontend/layouts/graphimages.blade.php
<div class="col-md-12">
    <div class="owl-carousel owl-theme fact-owl">
        @if(count(\App\Helper\Helper::getGraphBlocks())>0)
            @foreach(\App\Helper\Helper::getGraphBlocks() as $graphblocks)
                @php
                    $grandient_class = substr(str_shuffle('abcdefghijklmnopqrstuvwxyz') , 0 , 5 );
                @endphp

                <div class="item">
                    <div class="fact-box {{$grandient_class}}">
                        <div class="number-text">
                            <p class="fact-number"><span class="ft_count">{{$graphblocks->count}}</span> {{$graphblocks->title}} </p>
                            <p class="fact-text">{{$graphblocks->description}}</p>
                        </div>
                        <img src="{{asset('images/fact-img.png')}}" class="fact-img">
                    </div>
                    <style>
                        .fact-box.{{$grandient_class}} {
                            background: -webkit-gradient(linear, left top, right top, color-stop(-0.04%, {{$graphblocks->color}}), color-stop(100.04%, {{$graphblocks->color}}));
                            background: linear-gradient(90deg, {{$graphblocks->color}} -0.04%, {{$graphblocks->color}} 100.04%);
                        }
                    </style>
                </div>

            @endforeach
        @endif
    </div>
</div>

<script type="application/javascript">
    // fact owl
    $(function () {
        $('.fact-owl').owlCarousel({
            loop:true,
            margin:0,
//            nav:true,
            items: 5,
            width:100,
            autoplay:true,
            autoplayTimeout:2000,
            autoplayHoverPause:true,
            responsive: {
                1630:{
                    items:5
                },
                1260:{
                    items:4
                },
                900:{
                    items:3
                },
                700: {
                    items:2
                },
                0: {
                    items: 1
                }
            }
        })
    });

    $(".ft_count").delay(2000).each(function() {
        var mantissa = 0;
        var orig = $(this).text();
        if (orig.indexOf('.')>-1) {
            mantissa = orig.substring(orig.indexOf('.'))
        }
        $(this).prop('Counter', 0).animate({
            Counter: $(this).text()
        }, {
            duration: 2500,
            easing: 'swing',
            step: function(now) {
                $(this).text(Math.floor(now) + mantissa);
            },
        });
    });

</script>

resources/views/frontend/layouts/header.blade.php
<div class="profile-language">
    @if(\Illuminate\Support\Facades\Auth::user())

    {{--<form id="" class="">--}}
{{--        {{csrf_field()}}--}}
        <input type="search" placeholder="Search">
    {{--</form>--}}
    @endif

    <div class="dropdown profile-dropdown">
        @if(\Illuminate\Support\Facades\Auth::user())
            <a class="btn dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                @if(\Illuminate\Support\Facades\Auth::check() == 0)
                    <img src="{{asset('storage/user-img.png')}}" class="img-fluid" alt="">
                @else
                    <img src="{{asset('storage/'.\Illuminate\Support\Facades\Auth::user()->avatar)}}" class="img-fluid" alt="">
                @endif
               {!! \Illuminate\Support\Facades\Auth::check() ? '<span>'.ucfirst(\Illuminate\Support\Facades\Auth::user()->name).'</span>' : '' !!}
            </a>
        @else
           <ul class="navbar-nav">
               <li class="nav-item">
                   <a class="btn" href="{{route('frontend.login')}}">
                       @lang('auth.login')
                   </a>
               </li>
           </ul>
        @endif

        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" href="{{ route('voyager.dashboard') }}" target="_blank"><i class="fa fa-id-card" aria-hidden="true"></i> @lang('content.cabinet')</a>
            <a class="dropdown-item" href="{{route('frontend.logout')}}"><i class="fa fa-lock fa-1x"></i> @lang('auth.logout')</a>
        </div>

    </div>

    <div class="dropdown language-dropdown">
        <a class="btn dropdown-toggle" href="{{ url('locale/en') }}" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           {{ (\Illuminate\Support\Facades\Session::get('locale') ? strtoupper(\Illuminate\Support\Facades\Session::get('locale')) : config('baiterek.locales.KZ')) }}
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            @foreach(config('baiterek.locales') as $langs)
                @if(!empty(\Illuminate\Support\Facades\Session::get('locale')))
                    @if(strtoupper($langs) != strtoupper(\Illuminate\Support\Facades\Session::get('locale')))
                        <a class="dropdown-item" href="{{ url('locale/'.$langs) }}">{{strtoupper($langs)}}</a>
                    @endif
                @else
                    @if(strtoupper($langs)!='KZ')
                        <a class="dropdown-item" href="{{ url('locale/'.$langs) }}">{{strtoupper($langs)}}</a>
                    @endif
                @endif
            @endforeach
        </div>
    </div>
</div>

resources/views/frontend/layouts/homebanner.blade.php
@if(!empty(\App\Helper\Helper::getBannerCategoryBySlug('home-banner')))
@php  $homeBanner =\App\Helper\Helper::getBannerCategoryBySlug('home-banner'); @endphp
<div class="owl-carousel owl-theme homebanner">
    @if(count(\App\Helper\Helper::getBannersImages('home-banner'))>0)
        @foreach(\App\Helper\Helper::getBannersImages('home-banner') as $homebanners)
        <div class="item banner_item">
        <div class="slider-content" style="width:{{$homeBanner->width}}px;height:{{$homeBanner->height}}px;background-image: url({{asset('storage/'. $homebanners->image)}});">
                <div class="content">
                    <h3 style="color:{{$homebanners->title_color}}">{{$homebanners->title}}</h3>
                    <h1>{!! $homebanners->primary_text !!} </h1>
                    <p>{!! $homebanners->secondary_text !!}</p>
                    <a href="{{$homebanners->url}}" target="_blank" class="btn" style="color:{{$homebanners->url_text_color}}; border: 2px solid {{$homebanners->url_color}};">@if($homebanners->url_text != '') {{$homebanners->url_text}} @else @lang('auth.giveItTry') @endif</a>
                </div>
            </div>
        </div>
        @endforeach
    @endif
</div>

<script type="application/javascript">
// home banner
$(function () {
 $('.homebanner').owlCarousel({
     loop:true,
     margin:0,
     nav:true,
     items: 1,
     responsive:{
         0:{
             items:1
         },
         600:{
             items:1
         },
         1000:{
             items:1
         }
     }
 })
})

</script>
@endif

resources/views/frontend/layouts/homepagemiddleblock.blade.php
@if(!empty(\App\Helper\Helper::getBannerCategoryBySlug('home-page-middle-block')))
<div class="business-banner container-fluid" style="background-image:url({{asset('storage/' . \App\Helper\Helper::getBannersImages('home-page-middle-block')[0]->image)}})">
    <div class="row h-100">
        <div class="offset-lg-8 offset-md-6"></div>
        <div class="col-lg-4 col-md-6 black-div">
            @foreach(\App\Helper\Helper::getBannersImages('home-page-middle-block') as $homepagemiddleblock)
                <h3>{!! $homepagemiddleblock->primary_text !!}</h3>
                <p>{!! $homepagemiddleblock->secondary_text !!}</p>
            @endforeach
        </div>
    </div>
</div>
@endif

resources/views/frontend/layouts/menu.blade.php
<div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    {{menu('frontend','bootstrap',['locale' => app()->getLocale()])}}
</div>

resources/views/frontend/layouts/userHeader.blade.php
<img src="{{asset('images/logo.png')}}" alt="" title="">