routes/frontend.php
<?php
/**
 * Created by PhpStorm.
 * User: shruti
 * Date: 11/12/19
 * Time: 3:15 PM
 */

use Illuminate\Support\Facades\App;

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function (){
    Route::get('/', 'HomeController@index')->name('home.index');

    Route::get('news/{id}', function ($id) {
        return view('frontend.news.newsDetail', ['id'=> $id]);
    });

    Route::get('category/{id}', function ($id) {
        return App::call('App\Http\Controllers\Frontend\ProductController@getCategory', ['id' => $id]);
    });

    Route::get('services/{id}', function ($id) {
        return App::call('App\Http\Controllers\Frontend\ProductController@getProduct', ['id' => $id]);
    });

    Route::get('projects/{id}', function ($id) {
        return App::call('App\Http\Controllers\Frontend\ProjectsController@getProjects', ['id' => $id]);
    });

    Route::get('projectDetail/{id}', function ($id) {
        return App::call('App\Http\Controllers\Frontend\ProjectsController@projectDetail', ['id' => $id]);
    });

    Route::get('apply/{id}', function ($id) {
        return App::call('App\Http\Controllers\Frontend\ServiceRequestController@apply', ['id' => $id]);
    });

    Route::any('categories', 'ProductController@getAllCategories')->name('categories');
    Route::any('services', 'ProductController@index')->name('products');
    Route::any('projects', 'ProjectsController@index')->name('projects');
    Route::get('news', 'NewsController@index')->name('news');

    Route::get('login', 'CustomerController@index')->name('login');
    Route::post('authCheck', 'CustomerController@login')->name('authCheck');

    Route::get('register', 'CustomerController@register')->name('register');
    Route::get('checkEmail', 'CustomerController@checkEmail')->name('checkEmail');
    Route::get('checkVAT_no', 'CustomerController@checkVAT_no')->name('checkVAT_no');
    Route::post('save', 'CustomerController@save')->name('save');

    Route::get('forgot-password', 'ForgotPasswordController@forgotPassword')->name('forgotPassword');
    Route::post('email-reset-password-link', 'ForgotPasswordController@emailResetPasswordLink')->name('emailResetPasswordLink');
    Route::get('reset-password-form/{token}', 'ForgotPasswordController@resetPasswordForm')->name('resetPasswordForm');
    Route::post('save-password', 'ForgotPasswordController@savePassword')->name('savePassword');

    // request access
    Route::group(['middleware' => ['FrontendAuth','Security']], function(){

        Route::get('resetpassword', 'CustomerController@resetpassword')->name('resetpassword');
        Route::post('updatepassword', 'CustomerController@updatepassword')->name('updatepassword');

        Route::post('submitRequest', 'ServiceRequestController@submitRequest')->name('submitRequest');
        Route::get('applyNotification', 'ServiceRequestController@applyNotification')->name('applyNotification');

        Route::post('getDraftData', 'ServiceRequestController@getDraftData')->name('getDraftData');
        Route::post('applyService', 'ServiceRequestController@applyService')->name('applyService');
        Route::post('deleteDocument','ServiceRequestController@deleteDocument')->name('deleteDocument');

        Route::get('home-logout', 'CustomerController@logout')->name('logout');
    });

    Route::get('/{slug}', 'SegmentController@index')->name('cms.index');
});

routes/web.php
        Route::get('consulting-service-products/edit/{id}','Voyager\\ConsultingServiceProductController@edit')->name('voyager.consulting-service-products.edit');
        Route::put('consulting-service-products/update/{id}','Voyager\\ConsultingServiceProductController@update')->name('voyager.consulting-service-products.update');
        Route::delete('consulting-service-products/destroy/{id}','Voyager\\ConsultingServiceProductController@destroy')->name('voyager.consulting-service-products.destroy');

        // Projects
        Route::get('projects','Voyager\\ProjectsController@index')->name('voyager.projects.index');
        Route::post('projects','Voyager\\ProjectsController@index')->name('voyager.projects');
        Route::post('projects/browse','Voyager\\ProjectsController@browse')->name('voyager.projects.browse');
        Route::get('projects/create','Voyager\\ProjectsController@create')->name('voyager.projects.create');
        Route::post('projects/store','Voyager\\ProjectsController@store')->name('voyager.projects.store');
        Route::get('projects/edit/{id}','Voyager\\ProjectsController@edit')->name('voyager.projects.edit');
        Route::put('projects/update/{id}','Voyager\\ProjectsController@update')->name('voyager.projects.update');
        Route::delete('projects/destroy/{id}','Voyager\\ProjectsController@destroy')->name('voyager.projects.destroy');

        // Footer Widgets
        Route::get('footer-widgets','Voyager\\FooterWidgetsController@index')->name('voyager.footer-widgets.index');
        Route::post('footer-widgets','Voyager\\FooterWidgetsController@index')->name('voyager.footer-widgets');
        Route::post('footer-widgets/browse','Voyager\\FooterWidgetsController@browse')->name('voyager.footer-widgets.browse');
        Route::get('footer-widgets/create','Voyager\\FooterWidgetsController@create')->name('voyager.footer-widgets.create');
        Route::post('footer-widgets/store','Voyager\\FooterWidgetsController@store')->name('voyager.footer-widgets.store');
        Route::get('footer-widgets/edit/{id}','Voyager\\FooterWidgetsController@edit')->name('voyager.footer-widgets.edit');
        Route::put('footer-widgets/update/{id}','Voyager\\FooterWidgetsController@update')->name('voyager.footer-widgets.update');
        Route::delete('footer-widgets/destroy/{id}','Voyager\\FooterWidgetsController@destroy')->name('voyager.footer-widgets.destroy');


        /* ProductCategoriesController */
        Route::get('product-categories','Voyager\\ProductCategoriesController@index')->name('voyager.product-categories.index');
        Route::post('product-categories','Voyager\\ProductCategoriesController@index')->name('voyager.product-categories');
        Route::post('product-categories/browse','Voyager\\ProductCategoriesController@browse')->name('voyager.product-categories.browse');
        Route::get('product-categories/create','Voyager\\ProductCategoriesController@create')->name('voyager.product-categories.create');
        Route::post('product-categories/store','Voyager\\ProductCategoriesController@store')->name('voyager.product-categories.store');
        Route::get('product-categories/edit/{id}','Voyager\\ProductCategoriesController@edit')->name('voyager.product-categories.edit');
        Route::put('product-categories/update/{id}','Voyager\\ProductCategoriesController@update')->name('voyager.product-categories.update');
        Route::delete('product-categories/destroy/{id}','Voyager\\ProductCategoriesController@destroy')->name('voyager.product-categories.destroy');

        // Admin Media
//        Route::get('media/', ['uses' => 'Voyager\\VoyagerMediaController@index',              'as' => 'index']);
//        Route::post('files', ['uses' => 'Voyager\\VoyagerMediaController@files',              'as' => 'files']);
//        Route::post('new_folder', ['uses' => 'Voyager\\VoyagerMediaController@new_folder',         'as' => 'new_folder']);
//        Route::post('delete_file_folder', ['uses' => 'Voyager\\VoyagerMediaController@delete', 'as' => 'delete']);
//        Route::post('move_file', ['uses' => 'Voyager\\VoyagerMediaController@move',          'as' => 'move']);
//        Route::post('rename_file', ['uses' => 'Voyager\\VoyagerMediaController@rename',        'as' => 'rename']);
//        Route::post('upload', ['uses' => 'Voyager\\VoyagerMediaController@upload',             'as' => 'upload']);
//        Route::post('crop', ['uses' => 'Voyager\\VoyagerMediaController@crop',             'as' => 'crop']);

    });

});
Route::get('service-inquiries/ajaxCityList','Frontend\\CustomerController@ajaxCityList')->name('voyager.service-inquiries.ajaxCityList');
Route::get('invitation_check_dock/{id}', function($id){
//    try {
        $service_data = ServiceInquiryVerification::where('link', decrypt($id))->first();
        $serviceInquiryData = ServiceInquiries::where('id',$service_data->service_inquiry_id)->first();
        $service_form_data = [];
        $filesList = json_decode($service_data->path);
        foreach(json_decode($serviceInquiryData->fields) as $key => $form_data){
            if ($form_data->type == 'file'){
                $fileName = ServiceInquiriesDocuments::where('service_inquiries_id', $serviceInquiryData->id)->where('document', 'LIKE', $form_data->name.'%')->first();

                $customerFolder = $serviceInquiryData->user->name .'_'. $serviceInquiryData->user->id;
                $serviceInquiryVerificationId = $serviceInquiryData->id;
                $docPath = 'Documents/' . $customerFolder . '/' . $serviceInquiryVerificationId . '/' . $fileName->document;

                if($fileName){
                    if(in_array($fileName->document,array_values((Array)$filesList))) {
                        array_push($service_form_data, [
                            'type' => $form_data->type,
                            'title' => $form_data->label,
                            'value' => url('customerAttachmentDownload'). '?path='.$docPath
//                            'value' => asset('storage/documents/' . $fileName->document)
                        ]);
                    }
                }
            } else if($form_data->type == 'paragraph' || $form_data->type == 'header' || $form_data->type == 'hidden' || $form_data->type == 'button'){}else{
                try{
                    array_push($service_form_data,[
                        'type' => $form_data->type,
                        'title'  => $form_data->label,
                        'value'  => implode(', ', $form_data->userData)
                    ]);
                } catch (\Exception $s){
                    continue;
                }
            }
        }
        return view('frontend.tempUrl.verification', compact('service_data', 'service_form_data'));
//    }catch (Exception $e){
//        return abort(404);
//    }
})->name('invitationServiceInquiryVerification');

Route::any('action-services-inquiry-verification/{id}', function(\Illuminate\Http\Request $request, $id){
    app()->setLocale('kz');
    $docName = [];
    if($request->external_doc) {
        foreach ($request->external_doc as $key => $extDoc) {
            $image = $extDoc;
            $path = 'public/serviceInquiry/externalVerification/';
            $fileName = \Carbon\Carbon::now()->timestamp.$key. '.' . $image->getClientOriginalExtension();
            $storeFileName = 'serviceInquiry/externalVerification/' . $fileName;
            Storage::disk('local')->put($path . $fileName, file_get_contents($image));
            array_push($docName, $storeFileName);
        }
    }
    $service_data = ServiceInquiryVerification::where('id',$id)->first();
    $service_data->is_verified = $request->status == 1 ? ServiceInquiryVerification::VERIFICATION_YES : ServiceInquiryVerification::VERIFICATION_NO;
    $service_data->action_taken_at = \Carbon\Carbon::now();
    $service_data->comment = $request->comment;
    $service_data->documents = json_encode($docName);
    $service_data->save();

    ServiceInquiryActivity::create([
        'service_inquiry_id' => $service_data->service_inquiry_id,
        'user_id' => 0,
        'activity_type' => ServiceInquiryActivity::ACTIVITY_VERIFICATION,
        'message' => json_encode(['is_verified' => $service_data->is_verified, 'action_taken_at' => $service_data->action_taken_at, 'comment' => $service_data->comment, 'email' => $service_data->email, 'documents' => json_encode($docName)]),
        'requested_param' => serialize($request->except(['external_doc'])),
    ]);

    return back();
})->name('actionServiceInquiryVerification');

Route::post('CustomerFile', 'Voyager\\ServiceInquiryController@customerFile')->name('customerFile');

//Route::get('admin/login', ['uses' => 'Voyager\\VoyagerAuthController@login',     'as' => 'voyager.login']);
Route::get('admin/login', 'Frontend\CustomerController@index')->name('voyager.login');
Route::post('admin/login', ['uses' => 'Voyager\\VoyagerAuthController@postLogin', 'as' => 'voyager.postlogin']);

Route::get('customerAttachmentDownload',function(\Illuminate\Http\Request $request){

    /* DOWNLOAD FILE */
    try {
        $files = Storage::disk('sftp')->download($request->path);
        return $files;
    } catch (\Exception $e) {
        \Illuminate\Support\Facades\Log::notice('FILE DOWNLOAD ERROR '. $e->getMessage());
        return back();
    }
})->name('customerAttachmentDownload');

Route::get('download-file',function(\Illuminate\Http\Request $request){
//    dd($request->path);
//    $file = '/mig/savan.txt';
//    $content = 'BAITEREK 2020 PROJECT';
    /* STORE FILE */
//    Storage::disk('sftp')->put($file, $content);
    /****************END *****************/

    /* DOWNLOAD FILE */

    try {
        $files = Storage::disk('sftp')->download($request->path);
        return $files;
    } catch (\Exception $e) {
        \Illuminate\Support\Facades\Log::notice('FILE DOWNLOAD ERROR '. $e->getMessage());
        return back();
    }

app/Http/Controllers/API/ServiceRequestController.php
<?php

namespace App\Http\Controllers\API;

use App\Models\Products;
use App\Models\ServiceInquiries;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;

class ServiceRequestController extends BaseController
{
    public function getRequestList(Request $request,$num)
    {
        try{
            $lang = $request->lang;
            $role = \auth()->user()->role->slug;
            $requests = ServiceInquiries::with('product.userId')
                ->when($role, function ($query, $role) {
                    if ($role == 'customer') {
                        $query->where('user_id', \auth()->user()->id);
                    }
                })
                ->when($request->search_param, function ($query, $term) use ($lang) {
                    $query->whereHas('product', function (Builder $query2) use ($lang, $term) {
                        $query2->whereTranslation('title', 'LIKE', '%' . $term . '%', [$lang]);
                    });
                })->orderBy('id','desc')->get()
                ->map(function($item){
                    $product = Products::where('id',$item->product_id)->first()->translate('locale', $item->locale);
                    $item['product_title'] = !empty($product) ? $product->title : null;
                    $item['product']['title'] = !empty($product) ? $product->title : null;
                    return $item;
                })
                ->paginate($num);
            return $this->sendResponse($requests, 'Requests List',200);
        } catch (\Exception $e){
            return $this->sendResponse([], $e->getMessage(),401);
        }
    }
}

app/Http/Controllers/Frontend/CMSController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Helper\Helper;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use TCG\Voyager\Facades\Voyager;
use TCG\Voyager\Http\Controllers\Traits\BreadRelationshipParser;
use TCG\Voyager\Models\Page;

class CMSController extends \TCG\Voyager\Http\Controllers\Controller
{
    use BreadRelationshipParser;

    public function index(){

    }
}

app/Http/Controllers/Frontend/HomeController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index()
    {
        return view('frontend.master');
    }
}

app/Http/Controllers/Frontend/NewsController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\News;
use Illuminate\Http\Request;

class NewsController extends Controller
{
    public function index(){
        $news = News::all();

        return view('frontend.news.news',array('news' => $news));
    }
}

resources/views/frontend/serviceRequest/applyNotification.blade.php
@extends('frontend.master')

@section('content')
    <style>
        .sucess_apply_notification_img, .alert-danger, .alert-success{
            margin-left: auto;
            margin-right: auto;
        }
        .button_cus{
            box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.1);
            border-radius: 5px;
            padding: 10px 20px;
            font-size: 18px;
            line-height: 21px;
            text-align: center;
            text-transform: capitalize;
            color: black;
            margin: 0 10px;
            background: transparent;
            margin-bottom: 10px;
        }
        .button_cus:hover{
            color:white;
            background-color: #BBBEC3;
        }
        .ext_button{
            margin-left: auto;
            margin-right: auto;
            margin-top: 30px;
        }
    </style>
    <section class="">
        <div class="container-fluid">
            <div class="login-container">
                <img class="sucess_apply_notification_img" src="{{asset('images/apply-notification.png')}}">
                @if (session('error'))
                    <div class="alert alert-danger" role="alert">
                        <i class="fa fa-exclamation-triangle fa-1x"></i> {{ session('error') }}
                    </div>
                @endif

                @if (session('success'))
                    <div class="alert alert-success" role="alert">
                        <i class="fa fa-check-circle fa-1x"></i> {{ session('success') }}
                    </div>
                    <div class="ext_button" role="alert">
                        <a href="{{ route('frontend.products') }}" class="button_cus">{{ __('content.apply_for_more') }}</a>
                        <a href="{{ route('voyager.service-inquiries.index') }}" class="button_cus">{{ __('content.see_application_status') }}</a>
                    </div>
                @endif
            </div>
        </div>
    </section>
@endsection

<script>
    history.pushState(null, null, location.href);
    window.onpopstate = function (){
        history.go(1);
    };
</script>

resources/views/frontend/serviceRequest/draftApply.blade.php
@extends('frontend.master')

@section('content')
    <style>
        .btn-apply {
            background: #00803d !important;
            font-size: 14px;
            line-height: 21px;
            text-align: center;
            text-transform: capitalize;
            color: #ffffff;
            margin: 0 10px;
        }
        .btn-cancel {
            background: #c5c5c5 !important;
            height: 40px !important;
            font-size: 14px;
            border-radius: 3px;
            padding: 10px 20px;
            line-height: 21px;
            text-align: center;
            text-transform: capitalize;
            color: #ffffff;
            margin: 0 10px;
        }
        .preview-thumbnail {
            max-width:160px;
            height:auto;
            clear:both;
            display:block;
            padding:2px;
            border:1px solid #ddd;
        }
        .remove-preview {
            position: absolute;
            left: 25%;
            top: 30px;
            font-size: 16px;
            color: #c10000;
        }
    </style>
    <section class="">
        <div class="container-fluid">
            <div class="login-container">
                <h1 class="page_heading">@lang('fields.Apply Now') - <i>{{$product->title}}</i></h1>
                <form name="apply" id="apply" action="{{route('frontend.applyService')}}" method="POST" class="mt-3" enctype="multipart/form-data">
                    <div class="modal-body">
                        {{ csrf_field() }}
                        <input type="hidden" name="service_inquiry_id" id="service_inquiry_id" value="{{$serviceInquiryDetails->id}}">
                        <input type="hidden" name="service_inquiry_document_ids" id="service_inquiry_document_ids">
                        <input type="hidden" name="product_id" id="product_id" value="{{$serviceInquiryDetails->product_id}}">
                        <input type="hidden" name="formFields" id="formFields">
                        <input type="hidden" name="application_form_id" id="application_form_id" value="{{$serviceInquiryDetails->application_form_id}}">
                        <input type="hidden" name="status_of_request" id="status_of_request" value="{{$serviceInquiryDetails->status_of_request}}">
                        <input type="hidden" name="file_count" id="file_count">
                    <div id="fb-render">
                    </div>
                    <div class="form-row mt-5">
                        <div class="form-group col-md-12 d-flex align-items-center">
                            <input type="button" name="applyNow" id="applyNow" value="@lang('fields.Apply Now')" class="btn-apply" style="margin-left: 0;">
                            <a href="{{route('voyager.service-inquiries.index')}}" class="btn-cancel">@lang('content.cancel')</a>
                        </div>
                    </div>
                    @if(count($product->productCheckPoints))
                        <h3 class="doc_file_title">Download document here</h3>
                        <div class="doc_row row">
                            @foreach($product->productCheckPoints as $key => $productCheckpoint)
                                @if($productCheckpoint->type == \App\Models\ProductCheckPoint::DOCUMENT)
                                    <div class="doc_files col-md-2">
                                        <center>
                                            <a class="doc_ico" href="{{ asset('storage/'.$productCheckpoint->checkpoint) }}" target="_blank"><img src="{{ asset('images/doc-thumbnail.svg') }}"></a>
                                            <a class="doc_name" href="{{ asset('storage/'.$productCheckpoint->checkpoint) }}" download="">{{ $productCheckpoint->document_name }} <i class="fa fa-download download"></i> </a>
                                        </center>
                                    </div>
                                @endif
                            @endforeach
                        </div>
                    @endif
                </form>
            </div>
        </div>
    </section>

    <script src="{{asset('js/form-builder.min.js')}}"></script>
    <script src="{{asset('js/form-render.min.js')}}"></script>
    <script type="application/javascript">
        var formRender;
        $('document').ready(function () {
            const fbRender = document.getElementById("fb-render");
            const formData = JSON.stringify({!! $serviceInquiryDetails->fields !!});
            formRender = $(fbRender).formRender({ formData });

            $('.rendered-form').addClass('form-row');
            $( ".rendered-form" ).each(function() {
                $(this).find('div').addClass('form-group col-md-6');
            });


            $( "div.col-md-6" ).each(function(key,value) {
                if($(this).find('h1').length == 1){
                    $(this).removeClass().addClass('col-md-12 h1');

                }
                if( $(this).find('h2').length == 1){
                    $(this).removeClass().addClass('col-md-12 h2');

                }
                if($(this).find('h3').length == 1){
                    $(this).removeClass().addClass('col-md-12');

                }
                if($(this).find('h4').length == 1){
                    $(this).removeClass().addClass('col-md-12');

                }
                if($(this).find('h5').length == 1){
                    $(this).removeClass().addClass('col-md-12');

                }
                if($(this).find('h6').length == 1){
                    $(this).removeClass().addClass('col-md-12');

                }
                if($(this).find('p').length == 1){
                    $(this).removeClass().addClass('col-md-12');

                }
            });

            $.ajax({
                url: "{{ route('frontend.getDraftData') }}",
                type: 'POST',
                data: {
                    "_token" : "{{ csrf_token() }}",
                    'id': $('#service_inquiry_id').val(),
                },
                success: function (data) {
                    var service_inquiry_document_ids = [];
                    var file_count = 0;
                    $.each(data.serviceInquiryDocumentsDetails, function( index, value ) {
                        service_inquiry_document_ids.push(value.id);
                        service_inquiry_document_id = value.id;
                        service_inquiry_document_name = value.document;
                        $('input[type="file"]').each(function(i,v) {
                            var $this = $(this);
                            $nameArray = service_inquiry_document_name.split('_');
                            if ($nameArray[0] == $this.attr('name')) {
                                fileExtension = service_inquiry_document_name.substr((service_inquiry_document_name.lastIndexOf('.') + 1));
                                if (fileExtension == 'jpg' || fileExtension == 'png') {
                                    var route = '{{asset('storage/documents')}}'+'/'+service_inquiry_document_name;
                                    $this.parent().css('position', 'relative');
                                    $('<img src='+route+' class="preview-thumbnail">').insertAfter($this.parent().find('label'));
                                    $('<a target="_blank" href="'+route+'">'+service_inquiry_document_name+'</a>').insertAfter($this.parent().find('img'));
                                }
                                else {
                                    var route = '{{asset('storage/documents')}}'+'/'+service_inquiry_document_name;
                                    $this.parent().css('position', 'relative');
                                    $('<img src="{{asset('images/doc-thumbnail.svg')}}" class="preview-thumbnail">').insertAfter($this.parent().find('label'));
                                    $('<a target="_blank" href="'+route+'">'+service_inquiry_document_name+'</a>').insertAfter($this.parent().find('img'));
                                }
                            }
                        });
                    });
                    $('input[type="file"]').each(function() {
                        file_count++;
                    });
                    $('#service_inquiry_document_ids').val(service_inquiry_document_ids.join());
                    $('#file_count').val(file_count);
                },
                error: function () {
                    toastr.error("Oops something went wrong!");
                }
            });

            setTimeout(function(){
                $('#apply').find('.form-control').each(function() {
                    if ($(this).parent().find('img').length > 0) {
                        $(this).removeAttr('required');
                    }
                    var name = $(this).attr('name');
                    var required = $(this).attr('required');
                    var type = $(this).attr('type');
                    if(required != undefined) {
                        $('#apply').validate();
                        if (type == 'file') {
                            $("[name='" + name + "']").rules("add", {
                                required:true,
                                accept:"jpg,png,jpeg,doc,docx,pdf,csv",
                                messages: {
                                    required: "{{ __('validation.default_required') }}",
                                    accept: "{{ __('validation.default_accept') }}"
                                }
                            });
                        }
                        else {
                            $("[name='" + name + "']").rules("add", {
                                required:true,
                                messages: {
                                    required: "{{ __('validation.default_required') }}"
                                }
                            });
                        }
                    }
                    else {
                        if (type == 'file') {
                            $("[name='" + name + "']").rules("add", {
                                accept:"jpg,png,jpeg,doc,docx,pdf,csv",
                                messages: {
                                    accept: "{{ __('validation.default_accept') }}"
                                }
                            });
                        }
                    }
                });
            },1000);

            $('#applyNow').on('click', function(){
                var form_fields = JSON.stringify(formRender.userData);
                $('#formFields').val(form_fields);
                $('#status_of_request').val("{{ \App\Models\ServiceInquiries::APPLICATION_RECEIVED }}");
                if ($('#apply').valid()) {
                    $('form').submit();
                }
                else {
                    return false;
                }
            });

            $(document).on('click','.remove-preview',function(){
                var instance = $(this);
                var id = $(this).data('id');
                $.ajax({
                    url: "{{ route('frontend.deleteDocument') }}",
                    type: 'POST',
                    data: {
                        'id': id,
                    },
                    success: function (data) {
                        if (data.status) {
                            instance.parent().parent().find('img').remove();
                            instance.remove();
                        }
                        else {
                            console.log('Not able to delete');
                        }
                    },
                    error: function () {
                        toastr.error("Oops something went wrong!");
                    }
                });
            });
        });

    </script>
@endsection